# -*- coding: utf-8 -*-123
"""Another copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zszk-2AuzBrgikgrp2j9ztBoGtHCIvEx
"""

import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

df = pd.read_csv("Gathered_data.csv")

df['operating_system'].replace(0, 1, inplace=True)

X = df.drop(columns=['price(in rupees)', 'gpu_brand', 'cpu_model'])
y = df['price(in rupees)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2)

step1 = ColumnTransformer(transformers=[
    ('col_tnf', OneHotEncoder(drop='first'), [0, 1])  # Adjust column indexes if needed
], remainder='passthrough')

pipe = Pipeline([
    ('step1', step1),
    ('step2', LinearRegression())
])

pipe.fit(X_train, y_train)

with open("pipe.pkl", "wb") as f:
    pickle.dump(pipe, f)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score,mean_absolute_error
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor,ExtraTreesRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

df = pd.read_csv("Gathered_data.csv")
df

df['operating_system'].replace(0,1,inplace = True)
df['operating_system'].value_counts()

sns.distplot(df['price(in rupees)'])

df['brand'].value_counts().plot(kind='bar')

sns.barplot(x=df['brand'],y=df['price(in rupees)'])
plt.xticks(rotation='vertical')
plt.show()

sns.distplot(df['screen_size'])

sns.scatterplot(x=df['screen_size'],y=df['price(in rupees)'])

sns.barplot(x=df['operating_system'],y=df['price(in rupees)'])
plt.xticks(rotation='vertical')
plt.show()

df['touchscreen'].value_counts().plot(kind='bar')

sns.barplot(x=df['touchscreen'],y=df['price(in rupees)'])

X = df.drop(columns=['price(in rupees)','gpu_brand','cpu_model'])
y = np.array(df['price(in rupees)'])

X

y

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.15,random_state=2)

X_train

X_test

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(drop='first'),[0,1])
],remainder='passthrough')

step2 = LinearRegression()

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(drop='first'),[0,1])
],remainder='passthrough')

step2 = Ridge(alpha=10)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(drop='first'),[0,1])
],remainder='passthrough')

step2 = Lasso(alpha=0.001)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(drop='first'),[0,1])
],remainder='passthrough')

step2 = KNeighborsRegressor(n_neighbors=3)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(drop='first'),[0,1])
],remainder='passthrough')

step2 = DecisionTreeRegressor(max_depth=8)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(drop='first'),[0,1])
],remainder='passthrough')

step2 = RandomForestRegressor(n_estimators=100,
                              random_state=3,
                              max_samples=0.5,
                              max_features=0.75,
                              max_depth=15)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(drop='first'),[0,1])
],remainder='passthrough')

step2 = ExtraTreesRegressor(n_estimators=100,
                              random_state=3,
                              max_features=0.75,
                              max_depth=15)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

def predict_price(model, input_data):
    return model.predict(input_data)[0]

def format_laptops_multiline(df):
    if df.empty:
        return "No laptops found."
    return '\n\n'.join(df.apply(
        lambda x: f"Brand: {x['Company']}, Type: {x['TypeName']}, Price: ₹{x['Price']}, CPU: {x['Cpu']}, RAM: {x['Ram']}, Storage: {x['Memory']}",
        axis=1))

def find_price_range(price, buffer=5000):
    return price - buffer, price + buffer

brand = "HP"
cpuBrand = "Intel"
cpuGeneration = 11
cpuCores = 6
cpuThreads = 12
ram = 8
storage = 256
ssd = 1
hdd = 0
graphicVram = 0
battery = 70
operatingSystem = 1
screenSize = 15.6
ppi = 200
touchscreen = 0

yd = np.array([[
brand, cpuBrand, cpuGeneration, cpuCores, cpuThreads, ram, storage, ssd, hdd, graphicVram, battery, operatingSystem, screenSize, ppi, touchscreen
]])
prediction = pipe.predict(yd)

predicted_price = prediction[0]  # Access the first (and only) element in the array
print(f'The Predicted price with your specifications: {predicted_price}')

def find_ranges(num):
    str_num = str(num)
    first_digit = int(str_num[0])
    length = len(str_num)

    lowest_range = first_digit * (10 ** (length - 1))

    highest_range = (first_digit + 1) * (10 ** (length - 1))

    return lowest_range, highest_range

laptop = pd.read_csv("sample_laptop.csv")
laptop

min_price = int(input("Enter the minimum price: "))
max_price = int(input("Enter the maximum price: "))
brand = input("Enter the laptop brand (or leave blank for all): ").strip().lower()
filtered_laptops = laptop[laptop['Price'].between(min_price, max_price)]
if brand:
    filtered_laptops = filtered_laptops[filtered_laptops['Company'].str.lower() == brand]
def format_laptops_multiline(df):
    if df.empty:
        return "No laptops found."
    return '\n'.join(df.apply(
        lambda x: f"Brand: {x['Company']}, Type: {x['TypeName']}, Price: ₹{x['Price']}, CPU: {x['Cpu']}, RAM: {x['Ram']}, Storage: {x['Memory']}",
        axis=1))

print("\nLaptops in Selected Price Range:")
print(format_laptops_multiline(filtered_laptops))

predicted_price = int(input("Enter the predicted price: "))
brand = input("Enter the laptop brand: ")
def find_ranges(price):
    return price - 5000, price + 5000
low, high = find_ranges(predicted_price)
main_range = laptop[laptop['Price'].between(low, high)]
budget_range = laptop[laptop['Price'].between(35000, 45000)]
premium_range = laptop[laptop['Price'] > 100000]
main_range = main_range[main_range['Company'].str.lower() == brand.lower()]
budget_range = budget_range[budget_range['Company'].str.lower() == brand.lower()]
premium_range = premium_range[premium_range['Company'].str.lower() == brand.lower()]

def format_laptops_multiline(df):
    if df.empty:
        return "No laptops found."
    return '\n'.join(df.apply(
        lambda x: f"Brand: {x['Company']}, Type: {x['TypeName']}, Price: ₹{x['Price']}, CPU: {x['Cpu']}, RAM: {x['Ram']}, Storage: {x['Memory']}",
        axis=1))



print(" Laptops in Predicted Price Range:")
print(format_laptops_multiline(main_range), '\n')

low , high = find_ranges(int(predicted_price))
print(low ," " ,high)

result = laptop[laptop['Price'].between(low, high)]

result[result["Company"] == brand]

import pickle

pickle.dump(df,open('df.pkl','wb'))
pickle.dump(pipe,open('pipe.pkl','wb'))

import pandas as pd
laptop = pd.read_csv("sample_laptop.csv")

from IPython.display import display, clear_output
import ipywidgets as widgets
import pickle

df = pickle.load(open('df.pkl', 'rb'))
pipe = pickle.load(open('pipe.pkl', 'rb'))
laptop = pd.read_csv("sample_laptop.csv")

def feature_predict_price():
    brand = widgets.Dropdown(options=df['brand'].unique(), description='Brand')
    cpu_brand = widgets.Dropdown(options=df['cpu brand'].unique(), description='CPU Brand')
    cpu_gen = widgets.IntSlider(min=1, max=14, step=1, value=11, description='CPU Gen')
    cpu_cores = widgets.IntSlider(min=2, max=16, step=1, value=4, description='Cores')
    cpu_threads = widgets.IntSlider(min=2, max=32, step=2, value=8, description='Threads')
    ram = widgets.IntSlider(min=2, max=64, step=2, value=8, description='RAM')
    storage = widgets.IntSlider(min=128, max=2048, step=128, value=512, description='Storage')
    ssd = widgets.ToggleButtons(options=[0, 1], value=1, description='SSD')
    hdd = widgets.ToggleButtons(options=[0, 1], value=0, description='HDD')
    vram = widgets.IntSlider(min=0, max=8, step=1, value=2, description='VRAM')
    battery = widgets.IntSlider(min=20, max=100, step=5, value=50, description='Battery')
    os = widgets.ToggleButtons(options=[0, 1], value=1, description='OS')
    screen = widgets.FloatSlider(min=11.0, max=17.0, step=0.1, value=15.6, description='Screen')
    ppi = widgets.IntSlider(min=100, max=300, step=10, value=200, description='PPI')
    touch = widgets.ToggleButtons(options=[0, 1], value=0, description='Touch')

    output = widgets.Output()
    button = widgets.Button(description='Predict')

    def on_click(b):
        with output:
            clear_output()
            input_data = [[brand.value, cpu_brand.value, cpu_gen.value, cpu_cores.value,
                           cpu_threads.value, ram.value, storage.value, ssd.value, hdd.value,
                           vram.value, battery.value, os.value, screen.value, ppi.value, touch.value]]
            price = int(predict_price(pipe, input_data))
            print(f"💰 Predicted Price: ₹{price}")

    button.on_click(on_click)
    display(widgets.VBox([
        brand, cpu_brand, cpu_gen, cpu_cores, cpu_threads,
        ram, storage, ssd, hdd, vram, battery, os,
        screen, ppi, touch, button, output
    ]))

def feature_find_by_price_range():
    min_price = widgets.IntText(description="Min ₹", value=30000)
    max_price = widgets.IntText(description="Max ₹", value=60000)
    output = widgets.Output()
    button = widgets.Button(description='Search')

    def on_click(b):
        with output:
            clear_output()
            result = laptop[laptop['Price'].between(min_price.value, max_price.value)]
            print(format_laptops_multiline(result))

    button.on_click(on_click)
    display(widgets.VBox([min_price, max_price, button, output]))

def feature_find_by_price_and_brand():
    price = widgets.IntText(description='Price ₹', value=60000)
    brand = widgets.Dropdown(options=laptop['Company'].unique(), description='Brand')
    output = widgets.Output()
    button = widgets.Button(description='Find Laptops')

    def on_click(b):
        with output:
            clear_output()
            low, high = find_price_range(price.value)
            filtered = laptop[(laptop['Price'].between(low, high)) &
                              (laptop['Company'].str.lower() == brand.value.lower())]
            print(format_laptops_multiline(filtered))

    button.on_click(on_click)
    display(widgets.VBox([price, brand, button, output]))

menu = widgets.ToggleButtons(
    options=['1️⃣ Predict Price', '2️⃣ Laptops by Price Range', '3️⃣ Filter by Price & Brand'],
    description='Choose:',
    style={'description_width': 'initial'}
)

def menu_logic(change):
    clear_output()
    display(menu)
    if change['new'] == '1️⃣ Predict Price':
        feature_predict_price()
    elif change['new'] == '2️⃣ Laptops by Price Range':
        feature_find_by_price_range()
    elif change['new'] == '3️⃣ Filter by Price & Brand':
        feature_find_by_price_and_brand()

menu.observe(menu_logic, names='value')
display(menu)

import pandas as pd
import pickle

df = pd.read_csv("Gathered_data.csv")

df['operating_system'].replace(0, 1, inplace=True)

pickle.dump(df, open('df.pkl', 'wb'))

!pip install gradio

import gradio as gr
import pickle
import pandas as pd

df = pickle.load(open('df.pkl', 'rb'))
pipe = pickle.load(open('pipe.pkl', 'rb'))

def predict_price_web(brand, cpu_brand, cpu_gen, cpu_cores, cpu_threads, ram, storage,
                      ssd, hdd, vram, battery, os, screen, ppi, touch):
    input_data = [[brand, cpu_brand, cpu_gen, cpu_cores, cpu_threads,
                   ram, storage, ssd, hdd, vram, battery, os, screen, ppi, touch]]
    price = int(pipe.predict(input_data)[0])
    return f"💰 Estimated Price: ₹{price}"

brand_choices = df['brand'].unique().tolist()
cpu_brand_choices = df['cpu brand'].unique().tolist()

demo = gr.Interface(
    fn=predict_price_web,
    inputs=[
        gr.Dropdown(brand_choices, label="Brand"),
        gr.Dropdown(cpu_brand_choices, label="CPU Brand"),
        gr.Slider(1, 14, step=1, label="CPU Generation"),
        gr.Slider(2, 16, step=1, label="CPU Cores"),
        gr.Slider(2, 32, step=2, label="CPU Threads"),
        gr.Slider(2, 64, step=2, label="RAM (GB)"),
        gr.Slider(128, 2048, step=128, label="Storage (GB)"),
        gr.Radio([0, 1], label="SSD (1=Yes)"),
        gr.Radio([0, 1], label="HDD (1=Yes)"),
        gr.Slider(0, 8, step=1, label="VRAM (GB)"),
        gr.Slider(20, 100, step=5, label="Battery (Wh)"),
        gr.Radio([0, 1], label="Operating System Installed (1=Yes)"),
        gr.Slider(11.0, 17.0, step=0.1, label="Screen Size (inches)"),
        gr.Slider(100, 300, step=10, label="PPI"),
        gr.Radio([0, 1], label="Touchscreen (1=Yes)")
    ],
    outputs="text",
    title="💻 Laptop Price Predictor",
    description="Enter laptop specifications to predict the price"
)

# Launch the app
demo.launch(share=True)

print(df.columns)

import pandas as pd
import pickle

df = pd.read_csv("Gathered_data.csv")

df['operating_system'].replace(0, 1, inplace=True)

pickle.dump(df, open('df.pkl', 'wb'))

df = pickle.load(open('df.pkl', 'rb'))

# Clean the price column before using it
df['price(in rupees)'] = df['price(in rupees)'].astype(str).str.replace(r'[₹,]', '', regex=True)
df['price(in rupees)'] = pd.to_numeric(df['price(in rupees)'], errors='coerce')

df['price(in rupees)'] = df['price(in rupees)'].astype(str).str.replace(r'[₹,]', '', regex=True)
df['price(in rupees)'] = pd.to_numeric(df['price(in rupees)'], errors='coerce')

import gradio as gr
import pandas as pd
import pickle

# Load data
df = pickle.load(open('df.pkl', 'rb'))
pipe = pickle.load(open('pipe.pkl', 'rb'))

# Clean and prepare price column
df['price(in rupees)'] = df['price(in rupees)'].astype(str).str.replace(r'[₹,]', '', regex=True)
df['price(in rupees)'] = pd.to_numeric(df['price(in rupees)'], errors='coerce')

# Drop rows with invalid price just in case
df.dropna(subset=['price(in rupees)'], inplace=True)

# --- FUNCTION 1: Predict price from specs ---
def predict_price(brand, cpu_brand, cpu_gen, cpu_cores, cpu_threads, ram, storage,
                  ssd, hdd, vram, battery, os, screen, ppi, touch):
    input_data = [[brand, cpu_brand, cpu_gen, cpu_cores, cpu_threads,
                   ram, storage, ssd, hdd, vram, battery, os, screen, ppi, touch]]
    try:
        price = int(pipe.predict(input_data)[0])
        return f"💰 Estimated Price: ₹{price}"
    except Exception as e:
        return f"❌ Prediction Error: {str(e)}"

# --- FUNCTION 2: Filter laptops by price range ---
def filter_by_price_range(min_price, max_price):
    try:
        result = df[(df['price(in rupees)'] >= min_price) & (df['price(in rupees)'] <= max_price)]
        if result.empty:
            return "❌ No laptops found in this range."
        return result[['brand', 'cpu_model', 'price(in rupees)']].sort_values(by='price(in rupees)').to_string(index=False)
    except Exception as e:
        return f"❌ Error: {str(e)}"

# --- FUNCTION 3: Filter laptops by brand and price ---
def laptops_by_price_brand(price, brand):
    try:
        result = df[(df['price(in rupees)'] <= price) & (df['brand'] == brand)]
        if result.empty:
            return "❌ No laptops found for this brand within price."
        return result[['brand', 'cpu_model', 'price(in rupees)']].sort_values(by='price(in rupees)').to_markdown(index=False)
    except Exception as e:
        return f"❌ Error: {str(e)}"

# Dropdown lists
brand_list = df['brand'].dropna().unique().tolist()
cpu_brand_list = df['cpu brand'].dropna().unique().tolist()

# --- Gradio UI ---
with gr.Blocks(title="Laptop Insights") as demo:
    gr.Markdown("## 💻 Laptop Insights Web App")

    # Tab 1: Predict Price
    with gr.Tab("1️⃣ Predict Price"):
        gr.Markdown("Enter specifications to get laptop price estimate")
        with gr.Row():
            with gr.Column():
                brand = gr.Dropdown(brand_list, label="Brand")
                cpu_brand = gr.Dropdown(cpu_brand_list, label="CPU Brand")
                cpu_gen = gr.Slider(1, 14, step=1, label="CPU Generation")
                cpu_cores = gr.Slider(2, 16, step=1, label="CPU Cores")
                cpu_threads = gr.Slider(2, 32, step=2, label="CPU Threads")
                ram = gr.Slider(2, 64, step=2, label="RAM (GB)")
                storage = gr.Slider(128, 2048, step=128, label="Storage (GB)")
                ssd = gr.Radio([0, 1], label="SSD (1=Yes)")
                hdd = gr.Radio([0, 1], label="HDD (1=Yes)")
                vram = gr.Slider(0, 8, step=1, label="VRAM (GB)")
                battery = gr.Slider(20, 100, step=5, label="Battery (Wh)")
                os = gr.Radio([0, 1], label="OS Installed (1=Yes)")
                screen = gr.Slider(11.0, 17.0, step=0.1, label="Screen Size (inches)")
                ppi = gr.Slider(100, 300, step=10, label="PPI")
                touch = gr.Radio([0, 1], label="Touchscreen (1=Yes)")
                predict_btn = gr.Button("Predict Price")
            output1 = gr.Textbox(label="Estimated Price")
        predict_btn.click(
            fn=predict_price,
            inputs=[brand, cpu_brand, cpu_gen, cpu_cores, cpu_threads, ram, storage, ssd,
                    hdd, vram, battery, os, screen, ppi, touch],
            outputs=output1
        )

    # Tab 2: Laptops by Price Range
    with gr.Tab("2️⃣ Laptops by Price Range"):
        gr.Markdown("Get laptops between a price range")
        min_price = gr.Number(label="Min Price", value=30000)
        max_price = gr.Number(label="Max Price", value=70000)
        search_btn = gr.Button("Search")
        output2 = gr.Textbox(label="Matching Laptops", lines=10, interactive=False)
        search_btn.click(fn=filter_by_price_range, inputs=[min_price, max_price], outputs=output2)

    # Tab 3: Laptops by Brand and Max Price
    with gr.Tab("3️⃣ Laptops by Brand and Max Price"):
        gr.Markdown("Get laptops by selecting brand and max price")
        brand_in = gr.Dropdown(brand_list, label="Brand")
        max_price_in = gr.Number(label="Max Price")
        search_btn2 = gr.Button("Search")
        output3 = gr.Textbox(label="Matching Laptops", lines=10, interactive=False)
        search_btn2.click(fn=laptops_by_price_brand, inputs=[max_price_in, brand_in], outputs=output3)

# Run the app
demo.launch(share=True)
